ALTER TABLE phpbb_attachments DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_attachments CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_groups DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_groups CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_options DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_options CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_roles DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_roles CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_roles_data DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_roles_data CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_users DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_acl_users CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_banlist DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_banlist CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_bbcodes DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_bbcodes CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_bookmarks DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_bookmarks CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_bots DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_bots CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_config DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_config CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_confirm DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_confirm CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_disallow DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_disallow CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_drafts DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_drafts CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_extensions DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_extensions CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_extension_groups DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_extension_groups CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_forums DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_forums CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_forums_access DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_forums_access CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_forums_track DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_forums_track CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_forums_watch DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_forums_watch CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_groups DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_groups CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_icons DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_icons CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_lang DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_lang CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_log DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_log CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_login_attempts DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_login_attempts CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_moderator_cache DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_moderator_cache CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_modules DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_modules CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_poll_options DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_poll_options CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_poll_votes DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_poll_votes CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_post_rates DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_post_rates CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_posts DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_posts CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_privmsgs DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_privmsgs CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_privmsgs_folder DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_privmsgs_folder CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_privmsgs_rules DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_privmsgs_rules CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_privmsgs_to DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_privmsgs_to CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_profile_fields DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_profile_fields CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_profile_fields_data DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_profile_fields_data CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_profile_fields_lang DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_profile_fields_lang CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_profile_lang DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_profile_lang CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_ranks DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_ranks CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_reports DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_reports CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_reports_reasons DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_reports_reasons CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_search_results DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_search_results CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_search_wordlist DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_search_wordlist CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_search_wordmatch DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_search_wordmatch CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_sessions DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_sessions CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_sessions_keys DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_sessions_keys CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_sitelist DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_sitelist CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_smilies DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_smilies CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_template DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_template CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_template_data DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_template_data CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_theme DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_theme CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_imageset DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_imageset CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_imageset_data DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_styles_imageset_data CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_topics DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_topics CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_topics_track DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_topics_track CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_topics_posted DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_topics_posted CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_topics_watch DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_topics_watch CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_user_group DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_user_group CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_users DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_users CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_warnings DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_warnings CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_words DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_words CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_zebra DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_zebra CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_user_confirm_keys DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_user_confirm_keys CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_user_browser_ids DEFAULT CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;
ALTER TABLE phpbb_user_browser_ids CONVERT TO CHARACTER SET `utf8mb4` COLLATE `utf8mb4_bin`;

ALTER TABLE phpbb_posts MODIFY post_subject varchar(255) DEFAULT '' NOT NULL COLLATE utf8mb4_unicode_ci;
ALTER TABLE phpbb_topics MODIFY topic_title varchar(255) DEFAULT '' NOT NULL COLLATE utf8mb4_unicode_ci;
